services:
  damas-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: damas-online
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DOMAIN=damas.maroquio.com
    ports:
      - "3001:3001"  # Porta externa:porta interna (ambas 3001)
    volumes:
      - ./logs:/usr/src/app/logs
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"